# Generated by Django 5.1.6 on 2025-03-07 23:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SymptomLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(choices=[('happy', 'Happy'), ('neutral', 'Neutral'), ('anxious', 'Anxious'), ('depressed', 'Depressed'), ('stressed', 'Stressed')], default='neutral', max_length=20)),
                ('sleep_hours', models.FloatField(help_text='Number of hours slept')),
                ('physical_activity', models.PositiveIntegerField(default=0, help_text='Minutes of exercise')),
                ('appetite', models.CharField(help_text='Changes in appetite', max_length=50)),
                ('energy_levels', models.IntegerField(help_text='Scale: 1 (Low) - 10 (High)')),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation', models.TextField(help_text='AI-generated suggestion')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('symptom_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFeature.symptomlog')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WearableData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_rate', models.PositiveIntegerField(help_text='Heart Rate in BPM')),
                ('step_count', models.PositiveIntegerField(help_text='Steps walked today')),
                ('sleep_quality', models.CharField(help_text='Good, Moderate, Poor', max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
