# Generated by Django 5.1.6 on 2025-03-14 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFeature', '0004_bookappointment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MentalHealthAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood_level', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')])),
                ('emotional_state', models.CharField(choices=[('Happy', 'Happy'), ('Sad', 'Sad'), ('Anxious', 'Anxious'), ('Stressed', 'Stressed')], max_length=20)),
                ('sleep_hours', models.FloatField()),
                ('sleep_quality', models.CharField(choices=[('Good', 'Good'), ('Average', 'Average'), ('Poor', 'Poor')], max_length=20)),
                ('appetite_changes', models.CharField(choices=[('Increase', 'Increase'), ('Decrease', 'Decrease'), ('Normal', 'Normal')], max_length=20)),
                ('energy_levels', models.CharField(choices=[('Low', 'Low'), ('Normal', 'Normal'), ('High', 'High')], max_length=20)),
                ('interest_in_activities', models.CharField(choices=[('Normal', 'Normal'), ('Decreased', 'Decreased'), ('Lost', 'Lost')], max_length=20)),
                ('social_engagement', models.CharField(choices=[('Frequent', 'Frequent'), ('Occasional', 'Occasional'), ('Isolated', 'Isolated')], max_length=20)),
                ('suicidal_thoughts', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
