# Generated by Django 5.1.6 on 2025-04-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFeature', '0006_mentalhealthassessment_recommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentalhealthassessment',
            name='recommendation',
            field=models.JSONField(blank=True, help_text='AI-generated recommendation in JSON format', null=True),
        ),
    ]
