# Generated by Django 5.1.6 on 2025-04-16 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFeature', '0013_alter_bookappointment_patient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookappointment',
            options={},
        ),
        migrations.AlterField(
            model_name='bookappointment',
            name='appointment_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='bookappointment',
            name='provider',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bookappointment',
            name='reason',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bookappointment',
            name='time',
            field=models.TimeField(),
        ),
    ]
