# Generated by Django 5.1.6 on 2025-04-19 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFeature', '0015_alter_bookappointment_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookappointment',
            old_name='patient',
            new_name='patient_id',
        ),
    ]
