# Generated by Django 5.1.6 on 2025-04-19 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFeature', '0016_rename_patient_bookappointment_patient_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookappointment',
            old_name='patient_id',
            new_name='patient',
        ),
    ]
